

#增加用户信息
POST http://127.0.0.1:8080/jpa/addUser
Content-Type: application/json

{
  "id": 4,
  "name": "keer",
  "password": "133333",
  "address": "北京市平谷区"
}

###

#更改用户信息
POST http://127.0.0.1:8080/jpa/updateUser
Content-Type: application/json

{
  "id": 1,
  "name": "keer",
  "password": "133333",
  "address": "北京市平谷区"
}

###
#删除用户
POST http://127.0.0.1:8080/jpa/deleteUser
Content-Type: application/json

{
  "name": "java",
  "password": "hello world",
  "address": "main()",
  "id": 6
}

###
#批量增加用户
POST http://127.0.0.1:8080/jpa/addUsers
Content-Type: application/json

[
  {
    "name": "可耳",
    "password": "love",
    "address": "北京市"
  },
  {
    "name": "java",
    "password": "hello world",
    "address": "main()"
  }

]

###

#更改用户名
POST http://127.0.0.1:8080/jpa/updateUserNameById
Content-Type: application/json

{
  "id": 1,
  "name": "keer"
}

###

GET http://127.0.0.1:8080/jpa/selectAllUsers
Accept: application/json
###